### ISSUE TITLE
RM3 NullPointerException

### ISSUE THREAD

**Issue by davidmrau** [castorini/anserini#1640]
I am trying to run rm3 but get many `NullPointerExceptions` and it seems like the expansion isn't working, see output log at the very end.

I am running the following command:

```
../lib/anserini/target/appassembler/bin/SearchCollection -index ../indexes/msmarco/msmarco_passage/index-msmarco-passage-20191117-0ed488 \
 -topicreader TsvInt -topics ../collections/msmarco/test_2020/msmarco-test2020-queries.tsv \
 -output ../runs/run.msmarco-passage.bm25-rm3.topics.dl20.txt \
 -bm25 \
 -rm3 \
 -rm3.outputQuery \
 -rm3.fbTerms 50 
```

```
2021-09-23 10:13:45,025 INFO  [main] search.SearchCollection (SearchCollection.java:283) - ============ Initializing Searcher ============
2021-09-23 10:13:45,030 INFO  [main] search.SearchCollection (SearchCollection.java:284) - Index: ../indexes/msmarco/msmarco_passage/index-msmarco-passage-20191117-0ed488
2021-09-23 10:13:45,197 INFO  [main] search.SearchCollection (SearchCollection.java:364) - Language: en
2021-09-23 10:13:45,198 INFO  [main] search.SearchCollection (SearchCollection.java:365) - Stemmer: porter
2021-09-23 10:13:45,199 INFO  [main] search.SearchCollection (SearchCollection.java:366) - Keep stopwords? false
2021-09-23 10:13:45,199 INFO  [main] search.SearchCollection (SearchCollection.java:367) - Stopwords file null
2021-09-23 10:13:45,211 INFO  [main] search.SearchCollection (SearchCollection.java:578) - runtag: Anserini
2021-09-23 10:13:45,217 INFO  [main] search.SearchCollection (SearchCollection.java:584) - ============ Launching Search Threads ============
2021-09-23 10:13:45,226 INFO  [pool-2-thread-1] search.SearchCollection$SearcherThread (SearchCollection.java:182) - [Start] ranker: qld(mu=1000), reranker: rm3(fbTerms=50,fbDocs=10,originalQueryWeight=0.5)
java.lang.NullPointerException
	at io.anserini.rerank.lib.Rm3Reranker.createdFeatureVector(Rm3Reranker.java:194)
	at io.anserini.rerank.lib.Rm3Reranker.estimateRelevanceModel(Rm3Reranker.java:151)
	at io.anserini.rerank.lib.Rm3Reranker.rerank(Rm3Reranker.java:83)
	at io.anserini.rerank.RerankerCascade.run(RerankerCascade.java:64)
	at io.anserini.search.SearchCollection.search(SearchCollection.java:663)
	at io.anserini.search.SearchCollection$SearcherThread.run(SearchCollection.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
.
.
.
java.lang.NullPointerException
	at io.anserini.rerank.lib.Rm3Reranker.createdFeatureVector(Rm3Reranker.java:194)
	at io.anserini.rerank.lib.Rm3Reranker.estimateRelevanceModel(Rm3Reranker.java:151)
	at io.anserini.rerank.lib.Rm3Reranker.rerank(Rm3Reranker.java:83)
	at io.anserini.rerank.RerankerCascade.run(RerankerCascade.java:64)
	at io.anserini.search.SearchCollection.search(SearchCollection.java:663)
	at io.anserini.search.SearchCollection$SearcherThread.run(SearchCollection.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-09-23 10:13:45,785 INFO  [pool-2-thread-1] lib.Rm3Reranker (Rm3Reranker.java:99) - QID: 3505
2021-09-23 10:13:45,787 INFO  [pool-2-thread-1] lib.Rm3Reranker (Rm3Reranker.java:100) - Original Query: (how)^1.0 (do)^2.0 (heart)^1.0 (open)^1.0 (surgeri)^1.0
2021-09-23 10:13:45,788 INFO  [pool-2-thread-1] lib.Rm3Reranker (Rm3Reranker.java:101) - Running new query: (how)^0.083333336 (heart)^0.083333336 (do)^0.16666667 (open)^0.083333336 (surgeri)^0.083333336
```

**Comment by davidmrau** [comment]
Solved. Didn't store the Document Vectors in the index. Adding an error message might be helpful here.

**Comment by lintool** [comment]
Yes, agreed. A PR to fix would be appreciated! Or at least opening an issue to note the TODO.

**Comment by davidmrau** [comment]
I'll have a look!
