### ISSUE TITLE
Unable to run BEIR (v1.0.0): SPLADE++ CoCondenser-EnsembleDistil regressions

### ISSUE THREAD

**Issue by manveertamber** [castorini/anserini#2297]
I'm unable to run any of the SPLADE++ EnsembleDistil regressions. This command: `nohup python src/main/python/run_regression.py --index --verify --search --regression beir-v1.0.0-trec-covid-splade-pp-ed >& logs/log.beir-v1.0.0-trec-covid-splade-pp-ed &` gives output:

```
2023-12-07 12:27:40,208 INFO  [python] ========== Indexing ==========
2023-12-07 12:27:40,473 INFO  [python] target/appassembler/bin/IndexCollection -collection JsonVectorCollection -input /store/collections/beir-v1.0.0/splade-pp-ed/trec-covid -generator DefaultLuceneDocumentGenerator -index indexes/lucene-index.beir-v1.0.0-trec-covid-splade-pp-ed/ -threads 16 -impact -pretokenized -optimize
2023-12-07 12:27:43,428 INFO  [main] index.IndexCollection (IndexCollection.java:380) - Setting log level to INFO
2023-12-07 12:27:43,446 INFO  [main] index.IndexCollection (IndexCollection.java:383) - Starting indexer...
2023-12-07 12:27:43,446 INFO  [main] index.IndexCollection (IndexCollection.java:384) - ============ Loading Parameters ============
2023-12-07 12:27:43,447 INFO  [main] index.IndexCollection (IndexCollection.java:385) - DocumentCollection path: /store/collections/beir-v1.0.0/splade-pp-ed/trec-covid
2023-12-07 12:27:43,448 INFO  [main] index.IndexCollection (IndexCollection.java:386) - CollectionClass: JsonVectorCollection
2023-12-07 12:27:43,448 INFO  [main] index.IndexCollection (IndexCollection.java:387) - Generator: DefaultLuceneDocumentGenerator
2023-12-07 12:27:43,449 INFO  [main] index.IndexCollection (IndexCollection.java:388) - Threads: 16
2023-12-07 12:27:43,456 INFO  [main] index.IndexCollection (IndexCollection.java:389) - Language: en
2023-12-07 12:27:43,456 INFO  [main] index.IndexCollection (IndexCollection.java:390) - Stemmer: porter
2023-12-07 12:27:43,457 INFO  [main] index.IndexCollection (IndexCollection.java:391) - Keep stopwords? false
2023-12-07 12:27:43,457 INFO  [main] index.IndexCollection (IndexCollection.java:392) - Stopwords: null
2023-12-07 12:27:43,458 INFO  [main] index.IndexCollection (IndexCollection.java:393) - Store positions? false
2023-12-07 12:27:43,459 INFO  [main] index.IndexCollection (IndexCollection.java:394) - Store docvectors? false
2023-12-07 12:27:43,459 INFO  [main] index.IndexCollection (IndexCollection.java:395) - Store document "contents" field? false
2023-12-07 12:27:43,460 INFO  [main] index.IndexCollection (IndexCollection.java:396) - Store document "raw" field? false
2023-12-07 12:27:43,460 INFO  [main] index.IndexCollection (IndexCollection.java:397) - Additional fields to index: []
2023-12-07 12:27:43,461 INFO  [main] index.IndexCollection (IndexCollection.java:398) - Optimize (merge segments)? true
2023-12-07 12:27:43,461 INFO  [main] index.IndexCollection (IndexCollection.java:399) - Whitelist: null
2023-12-07 12:27:43,462 INFO  [main] index.IndexCollection (IndexCollection.java:400) - Pretokenized?: true
2023-12-07 12:27:43,462 INFO  [main] index.IndexCollection (IndexCollection.java:401) - Index path: indexes/lucene-index.beir-v1.0.0-trec-covid-splade-pp-ed/
2023-12-07 12:27:43,485 INFO  [main] index.IndexCollection (IndexCollection.java:481) - ============ Indexing Collection ============
2023-12-07 12:27:43,993 INFO  [main] index.IndexCollection (IndexCollection.java:510) - Thread pool with 16 threads initialized.
2023-12-07 12:27:43,993 INFO  [main] index.IndexCollection (IndexCollection.java:512) - Initializing collection in /store/collections/beir-v1.0.0/splade-pp-ed/trec-covid
2023-12-07 12:27:43,998 INFO  [main] index.IndexCollection (IndexCollection.java:521) - 32 files found
2023-12-07 12:27:43,998 INFO  [main] index.IndexCollection (IndexCollection.java:522) - Starting to index...
2023-12-07 12:28:44,242 INFO  [main] index.IndexCollection (IndexCollection.java:536) - 84.38% of files completed, 144,561 documents indexed
2023-12-07 12:29:14,970 INFO  [main] index.IndexCollection (IndexCollection.java:578) - Indexing Complete! 171,332 documents indexed
2023-12-07 12:29:14,971 INFO  [main] index.IndexCollection (IndexCollection.java:579) - ============ Final Counter Values ============
2023-12-07 12:29:14,972 INFO  [main] index.IndexCollection (IndexCollection.java:580) - indexed:          171,332
2023-12-07 12:29:14,972 INFO  [main] index.IndexCollection (IndexCollection.java:581) - unindexable:            0
2023-12-07 12:29:14,972 INFO  [main] index.IndexCollection (IndexCollection.java:582) - empty:                  0
2023-12-07 12:29:14,972 INFO  [main] index.IndexCollection (IndexCollection.java:583) - skipped:                0
2023-12-07 12:29:14,973 INFO  [main] index.IndexCollection (IndexCollection.java:584) - errors:                 0
2023-12-07 12:29:14,988 INFO  [main] index.IndexCollection (IndexCollection.java:587) - Total 171,332 documents indexed in 00:01:31
2023-12-07 12:29:15,865 INFO  [python] ========== Verifying Index ==========
2023-12-07 12:29:15,865 INFO  [python] target/appassembler/bin/IndexReaderUtils -index indexes/lucene-index.beir-v1.0.0-trec-covid-splade-pp-ed/ -stats
2023-12-07 12:29:17,166 INFO  [python] documents:             171332
2023-12-07 12:29:17,167 INFO  [python] documents (non-empty): 171332
2023-12-07 12:29:17,167 INFO  [python] total terms:           1206882333
2023-12-07 12:29:17,167 INFO  [python] Index statistics successfully verified!
2023-12-07 12:29:17,167 INFO  [python] ========== Ranking ==========
2023-12-07 12:29:17,198 INFO  [python] target/appassembler/bin/SearchCollection -index indexes/lucene-index.beir-v1.0.0-trec-covid-splade-pp-ed/ -topics tools/topics-and-qrels/topics.beir-v1.0.0-trec-covid.test.splade-pp-ed.tsv.gz -topicReader TsvString -output runs/run.beir-v1.0.0-trec-covid-splade-pp-ed.test.splade-pp-ed -impact -pretokenized -removeQuery -hits 1000
"-topicReader" is not a valid option
 -analyzeWithHuggingFaceTokenizer VAL : search a collection by tokenizing query with pretrained
                                        mbert tokenizer
 -arbitraryScoreTieBreak              : Break score ties arbitrarily (not recommended) (default:
                                        false)
 -axiom                               : use Axiomatic query expansion model for the reranking
                                        (default: false)
 -axiom.beta STRING[]                 : parameter beta for Axiomatic query expansion model
                                        (default: 0.4)
 -axiom.deterministic                 : make the expansion terms axiomatic reranking results
                                        deterministic (default: false)
 -axiom.docids VAL                    : sorted docids file that for deterministic reranking. this
                                        file can be obtained by running CLI command `IndexUtils
                                        -index /path/to/index -dumpAllDocids GZ`
 -axiom.index VAL                     : path to the external index for generating the reranking
                                        doucments pool
 -axiom.n STRING[]                    : parameter N in axiomatic reranking (default: 30)
 -axiom.outputQuery                   : output original and expanded query (default: false)
 -axiom.r STRING[]                    : parameter R in axiomatic reranking (default: 20)
 -axiom.seed STRING[]                 : seed for the random generator in axiomatic reranking
                                        (default: 42)
 -axiom.top STRING[]                  : select top M terms from the expansion terms pool (default:
                                        20)
 -backgroundlinking                   : performs the background linking task as part of the TREC
                                        News Track (default: false)
 -backgroundlinking.datefilter        : Boolean switch to filter out articles published after topic
                                        article for the TREC News Track Background Linking task.
                                        (default: false)
 -backgroundlinking.k N               : extract top k terms from the query document for TREC News
                                        Track Background Linking task. The terms are ranked by
                                        their tf-idf score from the query document (default: 10)
 -bm25                                : ranking model: BM25 (default: false)
 -bm25.accurate                       : BM25: use accurate document lengths (default: false)
 -bm25.b STRING[]                     : BM25: b parameter (default: 0.4)
 -bm25.k1 STRING[]                    : BM25: k1 parameter (default: 0.9)
 -bm25prf                             : use bm25PRF query expansion model (default: false)
 -bm25prf.b STRING[]                  : bm25PRF parameter: b (default: 0.4)
 -bm25prf.fbDocs STRING[]             : bm25PRF parameter: number of documents (default: 10)
 -bm25prf.fbTerms STRING[]            : bm25PRF parameter: number of expansion terms (default: 20)
 -bm25prf.k1 STRING[]                 : bm25PRF parameter: k1 (default: 0.9)
 -bm25prf.newTermWeight STRING[]      : bm25PRF parameter: weight to assign to the expansion terms
                                        (default: 0.2)
 -bm25prf.outputQuery                 : bm25PRF parameter: print original and expanded queries
                                        (default: false)
 -collection [class]                  : If doc vector is not stored in the index, this need to be
                                        provided as collection class in package
                                        'io.anserini.collection'.
 -encoder VAL                         : Query encoder for supervised sparse retrieval tasks
 -f2exp                               : use F2Exp scoring model (default: false)
 -f2exp.s [value]                     : F2Exp s parameter (default: 0.5)
 -f2log                               : use F2Log scoring model (default: false)
 -f2log.s [value]                     : F2Log s parameter (default: 0.5)
 -fields [file]                       : Fields
 -format [output format]              : Output format, default "trec", alternative "msmarco".
                                        (default: trec)
 -hits [number]                       : max number of hits to return (default: 1000)
 -impact                              : ranking model: BM25 (default: false)
 -index [path]                        : Path to Lucene index
 -inl2                                : use I(n)L2 scoring model (default: false)
 -inl2.c [value]                      : I(n)L2 c parameter (default: 0.1)
 -inmem                               : Boolean switch to read index in memory (default: false)
 -keepstopwords                       : Boolean switch to keep stopwords in the query topics
                                        (default: false)
 -language VAL                        : Analyzer Language (default: en)
 -output [file]                       : output file
 -parallelism [int]                   : Number of threads to use for each individual parameter
                                        configuration. (default: 8)
 -pretokenized                        : Boolean switch to accept pre tokenized jsonl. (default:
                                        false)
 -qid_queries [file]                  : query id - query mapping file (default: )
 -qld                                 : ranking model: query likelihood with Dirichlet smoothing
                                        (default: false)
 -qld.mu STRING[]                     : qld: mu smoothing parameter (default: 1000)
 -qljm                                : ranking model: query likelihood with Jelinek-Mercer
                                        smoothing (default: false)
 -qljm.lambda STRING[]                : qljm: lambda smoothing parameter (default: 0.1)
 -querygenerator VAL                  : QueryGenerator to use. (default: BagOfWordsQueryGenerator)
 -removeQuery                         : Remove docids that have the query id when writing final run
                                        output. (default: false)
 -removedups                          : Remove duplicate docids when writing final run output.
                                        (default: false)
 -rerankCutoff [number]               : max number of hits for the initial round ranking. this is
                                        efficient since lots of reranking model only looks at the
                                        top documents from the initial round ranking. (default: 50)
 -rf.qrels [file]                     : qrels file used for relevance feedback
 -rm3                                 : use RM3 query expansion model (default: false)
 -rm3.fbDocs STRING[]                 : RM3 parameter: number of expansion documents (default: 10)
 -rm3.fbTerms STRING[]                : RM3 parameter: number of expansion terms (default: 10)
 -rm3.noTermFilter                    : RM3 parameter: turn off English term filter (default: false)
 -rm3.originalQueryWeight STRING[]    : RM3 parameter: weight to assign to the original query
                                        (default: 0.5)
 -rm3.outputQuery                     : RM3 parameter: flag to print original and expanded queries
                                        (default: false)
 -rocchio                             : use rocchio query expansion model (default: false)
 -rocchio.alpha STRING[]              : Rocchio parameter: weight to assign to the original query
                                        (default: 1)
 -rocchio.beta STRING[]               : Rocchio parameter: weight to assign to the relevant
                                        document vectors (default: 0.75)
 -rocchio.bottomFbDocs STRING[]       : Rocchio parameter: number of expansion nonrelevant
                                        documents (default: 10)
 -rocchio.bottomFbTerms STRING[]      : Rocchio parameter: number of expansion nonrelevant terms
                                        (default: 10)
 -rocchio.gamma STRING[]              : Rocchio parameter: weight to assign to the nonrelevant
                                        document vectors (default: 0.15)
 -rocchio.outputQuery                 : Rocchio parameter: flag to print original and expanded
                                        queries (default: false)
 -rocchio.topFbDocs STRING[]          : Rocchio parameter: number of expansion relevant documents
                                        (default: 10)
 -rocchio.topFbTerms STRING[]         : Rocchio parameter: number of expansion relevant terms
                                        (default: 10)
 -rocchio.useNegative                 : Rocchio parameter: flag to use nonrelevant document vectors
                                        (default: false)
 -runtag [tag]                        : runtag
 -sdm                                 : boolean switch to use Sequential Dependence Model query
                                        (default: false)
 -sdm.ow [value]                      : ordered window weight in sdm (default: 0.1)
 -sdm.tw [value]                      : SDM term weight (default: 0.85)
 -sdm.uw [value]                      : unordered window weight in sdm (default: 0.05)
 -searchtweets                        : Whether the search is against a tweet index created by
                                        IndexCollection -collection TweetCollection (default: false)
 -selectMaxPassage                    : Select and retain only the max scoring segment from each
                                        document. (default: false)
 -selectMaxPassage.delimiter [regexp] : The delimiter (as a regular regression) for splitting the
                                        segment id from the doc id. (default: \.)
 -selectMaxPassage.hits [int]         : Maximum number of hits to return per topic after segment id
                                        removal. Note that this is different from '-hits', which
                                        specifies the number of hits including the segment id. 
                                        (default: 2147483647)
 -skipexists                          : When enabled, will skip if the run file exists (default:
                                        false)
 -spl                                 : use SPL scoring model (default: false)
 -spl.c [value]                       : SPL c parameter (default: 0.1)
 -stemmer VAL                         : Stemmer: one of the following porter,krovetz,none. Default
                                        porter (default: porter)
 -stopwords [file]                    : Path to file with stopwords.
 -threads [int]                       : Number of threads to use for running different parameter
                                        configurations. (default: 1)
 -topicfield VAL                      : Which field of the query should be used, default "title".
                                        For TREC ad hoc topics, description or narrative can be
                                        used. (default: title)
 -topicreader VAL                     : TopicReader to use.
 -topics [file]                       : topics file
 -useAutoCompositeAnalyzer            : index a collection using the useAutoCompositeAnalyzer
                                        (default: false)
 -useCompositeAnalyzer                : search a collection using a Lucene Analyzer & a pretrained
                                        HuggingFace tokenizer (default: false)
Example: SearchCollection -index [path] -output [file] -topicreader VAL -topics [file]
2023-12-07 12:29:19,328 INFO  [python] ========== Verifying Results: beir-v1.0.0-trec-covid-splade-pp-ed ==========
trec_eval.get_results: Cannot read results file 'runs/run.beir-v1.0.0-trec-covid-splade-pp-ed.test.splade-pp-ed'
trec_eval: Quit in file 'runs/run.beir-v1.0.0-trec-covid-splade-pp-ed.test.splade-pp-ed'
Traceback (most recent call last):
  File "src/main/python/run_regression.py", line 418, in <module>
    evaluate_and_verify(yaml_data, args.dry_run)
  File "src/main/python/run_regression.py", line 196, in evaluate_and_verify
    check_output(' '.join(eval_cmd)).decode('utf-8').split('\n') if line.strip()][-1]
  File "src/main/python/run_regression.py", line 82, in check_output
    raise RuntimeError("Command {0} running unsuccessfully".format(command))
RuntimeError: Command tools/eval/trec_eval.9.0.4/trec_eval -c -m ndcg_cut.10 tools/topics-and-qrels/qrels.beir-v1.0.0-trec-covid.test.txt runs/run.beir-v1.0.0-trec-covid-splade-pp-ed.test.splade-pp-ed running unsuccessfully
```

**Comment by manveertamber** [comment]
forgot to re-build. works now.
