### ISSUE TITLE
Maven build / test issue

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [castorini/anserini#2364]
Following the readme instructions, clone with recursive and mvn clean package appassembler:assemble throws the below.

It used to build fine a couple of weeks ago.

OS details:

```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< io.anserini:anserini >------------------------
[INFO] Building Anserini 0.24.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
:
:
[INFO] Running io.anserini.encoder.SpladePlusPlusEnsembleDistilEncoderInferenceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 56.115 s <<< FAILURE! - in io.anserini.encoder.SpladePlusPlusEnsembleDistilEncoderInferenceTest
[ERROR] io.anserini.encoder.SpladePlusPlusEnsembleDistilEncoderInferenceTest.basic  Time elapsed: 56.113 s  <<< ERROR!
ai.onnxruntime.OrtException: 
Error code - ORT_FAIL - message: Load model from /root/.cache/anserini/test/splade-pp-ed-optimized.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 4 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 3.

	at ai.onnxruntime.OrtSession.createSession(Native Method)
	at ai.onnxruntime.OrtSession.<init>(OrtSession.java:74)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:236)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:221)
	at io.anserini.encoder.SpladePlusPlusEncoderInferenceTest.basicTest(SpladePlusPlusEncoderInferenceTest.java:42)
	at io.anserini.encoder.SpladePlusPlusEnsembleDistilEncoderInferenceTest.basic(SpladePlusPlusEnsembleDistilEncoderInferenceTest.java:225)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
: 
: 
[ERROR] Errors: 
[ERROR]   SpladePlusPlusEnsembleDistilEncoderInferenceTest.basic:225->SpladePlusPlusEncoderInferenceTest.basicTest:42 » Ort Error code - ORT_FAIL - message: Load model from /root/.cache/anserini/test/splade-pp-ed-optimized.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 4 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 3.

[ERROR]   SimpleImpactSearcherTest.testOnnxEncoder:239 » Runtime java.lang.reflect.InvocationTargetException
[INFO] 
[ERROR] Tests run: 743, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:45 min
[INFO] Finished at: 2024-02-09T08:13:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.0:test (default-test) on project anserini: 
```

**Comment by lintool** [comment]
Apologies, @ArthurChen189 was working on #2354 to fix an error - by updating the ONNX model - but broke something in the process. I've reverted to the old model version.

**Comment by PrithivirajDamodaran** [comment]
No Apology needed, thanks for the update and quick turnaround.
