### ISSUE TITLE
java.lang.SecurityException in latest main trunk

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#2625]
At Anserini commit [`e2eb20`](https://github.com/castorini/anserini/commit/e2eb203b83dd643a356ee90f299c8877f6e108bd) (2024/10/22).

Build is successful, but I am able to confirm the `java.lang.SecurityException`:

```bash
% bin/run.sh io.anserini.index.IndexCollection \
  -collection JsonCollection \
  -input collections/msmarco-passage/collection_jsonl \
  -index indexes/msmarco-passage/lucene-index-msmarco \
  -generator DefaultLuceneDocumentGenerator \
  -threads 9 -storePositions -storeDocvectors -storeRaw
WARNING: Using incubator modules: jdk.incubator.vector
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:320)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:232)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:760)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1070)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:42)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:867)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:797)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:692)
```

Previously reported in these PRs:

+ https://github.com/castorini/anserini/pull/2615 (September 27)
+ https://github.com/castorini/anserini/pull/2621 (October 16)
+ https://github.com/castorini/anserini/pull/2623 (October 20)
+ https://github.com/castorini/anserini/pull/2624 (October 25)

I can also confirm that #2624 fixes the issue.

**Comment by lintool** [comment]
Closed by #2624
