### ISSUE TITLE
clueweb12-b13 regression is broken

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#287]
clueweb12-b13 regression broke recently:

```
nohup python src/main/python/run_regression_clueweb12-b13.py > log.clueweb12-b13 &
```
Log output:

```
...
trec_eval.form_res_qrels: duplicate docs clueweb12-0000wb-07-13559trec_eval: Can't calculate measure 'map'
True
Topics 701-750: bm25     : map  : 0.0457 0.0457
Topics 751-800: bm25     : map  : 0.0219 0.0219
Traceback (most recent call last):
  File "src/main/python/run_regression_clueweb12-b13.py", line 61, in <module>
    actual_t1_map = trec_eval_metric("map", t1_qrels, "run.web.201-250.bm25+rm3.txt")
  File "src/main/python/run_regression_clueweb12-b13.py", line 30, in trec_eval_metric
    return float(os.popen("eval/trec_eval.9.0/trec_eval -m {} {} {}".format(metric, qrels, run)).read().split("\t")[2].strip())
IndexError: list index out of range
```

I came across this as part of running regression tests for #281.

I'm looking into it...

**Comment by lintool** [comment]
False alarm. What happened is that I had both these running at the same time:
```
nohup python src/main/python/run_regression_clueweb12-b13.py > log.clueweb12-b13 &
nohup python src/main/python/run_regression_clueweb12.py > log.clueweb12 &
```
They write to the same output file, and thus mangling the formatting.

Confirmed on current master that `run_regression_clueweb12-b13.py` works fine.
