### ISSUE TITLE
Error when dump raw docs on Robust04: requested size exceeds TarArchiveEntry set size

### ISSUE THREAD

**Issue by Kytabyte** [castorini/Anserini#325]
When I try to dump raw docs on Robust04 collection, I ran

```
sh target/appassembler/bin/IndexUtils -index lucene-index.robust04.pos+docvectors+rawdocs/ \
-dumpRawDocs lucene-index.robust04.pos+docvectors+rawdocs.allDocids.txt
```

I got
```
Exception in thread "main" java.io.IOException: request to write '24645' bytes exceeds size in header of '24627' bytes for entry 'FBIS3-20646'
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:382)
	at java.io.OutputStream.write(OutputStream.java:75)
	at io.anserini.index.IndexUtils.dumpRawDocuments(IndexUtils.java:361)
	at io.anserini.index.IndexUtils.main(IndexUtils.java:456
```

I'm having the same problem while I'm using the same idea to write code for dumping out document vectors. I think this is because it uses `String.length()` to set the initial size of a `TarArchiveEntry`, which may not match the size of some UTF-8 char when writing.

**Comment by lintool** [comment]
@Kytabyte seems to be solved, so I'm closing...
