### ISSUE TITLE
Error in new regression script: core17

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#356]
At commit 5f8c26d328dd67e6cc538d5f9b4af44acdbc74e5 - newly merged regression framework.

Invocation:

```
nohup python src/main/python/run_regression.py --collection core17 --index >& log.core17 &
```
Error:

```
...
2018-07-21 12:18:21,729 INFO  [main] index.IndexCollection (IndexCollection.java:346) - # Final Counter Values
2018-07-21 12:18:21,730 INFO  [main] index.IndexCollection (IndexCollection.java:347) - indexed:        1,831,109
2018-07-21 12:18:21,730 INFO  [main] index.IndexCollection (IndexCollection.java:348) - empty:             24,550
2018-07-21 12:18:21,730 INFO  [main] index.IndexCollection (IndexCollection.java:349) - unindexed:         24,550
2018-07-21 12:18:21,730 INFO  [main] index.IndexCollection (IndexCollection.java:350) - unindexable:            0
2018-07-21 12:18:21,731 INFO  [main] index.IndexCollection (IndexCollection.java:351) - skipped:                0
2018-07-21 12:18:21,731 INFO  [main] index.IndexCollection (IndexCollection.java:352) - errors:                 0
2018-07-21 12:18:21,738 INFO  [main] index.IndexCollection (IndexCollection.java:355) - Total 1,831,109 documents indexed in 00:08:05
========== Indexing ==========
target/appassembler/bin/IndexCollection -collection NewYorkTimesCollection -generator JsoupGenerator -threads 16 -input /tuna1/collections/newswire/NYTcorpus/ -index lucene-index.core17.pos+docvectors -storePositions -storeDocvectors -optimize
========== Indexing ==========
========== Verifying Index ==========
[Index] lucene-index.core17.pos+docvectors
documents:             1831109
documents (non-empty): 1831109
total terms:           720510677
 ========== Verifying Index Succeed ========== 
========== Ranking ==========
Traceback (most recent call last):
  File "src/main/python/run_regression.py", line 187, in <module>
    run_cmds = construct_ranking_command(yaml_data, args.index)
  File "src/main/python/run_regression.py", line 112, in construct_ranking_command
    for (model, topic) in list(itertools.product(yaml_data['models'], yaml_data['topics']))
KeyError: 'topic_reader'
```

**Comment by Peilin-Yang** [comment]
The output should be b/c of using `print` instead of `logging`?
I will address this in another PR?

**Comment by lintool** [comment]
Let me gather up all the issues I've encountered and you can fix all at once?

Also, let's start a file in `docs/` that documents whenever the regression numbers change and other major regression events? Let's note the commit id, time, etc.

We should also add my RM3 patch from a while ago.

The point is that we should be able to reconstruct every time a regression number changes, exactly.

**Comment by lintool** [comment]
I've run the following regressions:

```
nohup python src/main/python/run_regression.py --collection disk12 --index >& log.disk12 &
nohup python src/main/python/run_regression.py --collection robust04 --index >& log.robust04 &
nohup python src/main/python/run_regression.py --collection robust05 --index >& log.robust05 &
nohup python src/main/python/run_regression.py --collection core17 --index >& log.core17 &

nohup python src/main/python/run_regression.py --collection mb11 --index >& log.mb11 &
nohup python src/main/python/run_regression.py --collection mb13 --index >& log.mb13 &

nohup python src/main/python/run_regression.py --collection wt10g --index >& log.wt10g &
nohup python src/main/python/run_regression.py --collection gov2 --index >& log.gov2 &
nohup python src/main/python/run_regression.py --collection cw09b --index >& log.cw09b &
nohup python src/main/python/run_regression.py --collection cw12b13 --index >& log.cw12b13 &
```

Note, not the full cw12 (yet), and core17 has issues.

**Comment by lintool** [comment]
For all the regression scripts, I now get:

```
2018-07-22 08:00:06,928 - regression_test - INFO - ==========Verifying Results==========
2018-07-22 08:00:07,043 - regression_test - INFO - {"actual": 0.1996, "collection": "core17", "expected": 0.1996, "metric": "map", "model": "bm25", "topic": "All Topics"}
2018-07-22 08:00:07,125 - regression_test - INFO - {"actual": 0.4207, "collection": "core17", "expected": 0.4207, "metric": "p30", "model": "bm25", "topic": "All Topics"}
2018-07-22 08:00:07,208 - regression_test - INFO - {"actual": 0.2633, "collection": "core17", "expected": 0.2633, "metric": "map", "model": "bm25+rm3", "topic": "All Topics"}
2018-07-22 08:00:07,294 - regression_test - INFO - {"actual": 0.4893, "collection": "core17", "expected": 0.4893, "metric": "p30", "model": "bm25+rm3", "topic": "All Topics"}
2018-07-22 08:00:07,380 - regression_test - INFO - {"actual": 0.2719, "collection": "core17", "expected": 0.2719, "metric": "map", "model": "bm25+ax", "topic": "All Topics"}
2018-07-22 08:00:07,466 - regression_test - INFO - {"actual": 0.49, "collection": "core17", "expected": 0.49, "metric": "p30", "model": "bm25+ax", "topic": "All Topics"}
2018-07-22 08:00:07,550 - regression_test - INFO - {"actual": 0.1928, "collection": "core17", "expected": 0.1928, "metric": "map", "model": "ql", "topic": "All Topics"}
2018-07-22 08:00:07,634 - regression_test - INFO - {"actual": 0.4327, "collection": "core17", "expected": 0.4327, "metric": "p30", "model": "ql", "topic": "All Topics"}
2018-07-22 08:00:07,724 - regression_test - INFO - {"actual": 0.2409, "collection": "core17", "expected": 0.2409, "metric": "map", "model": "ql+rm3", "topic": "All Topics"}
2018-07-22 08:00:07,808 - regression_test - INFO - {"actual": 0.4647, "collection": "core17", "expected": 0.4647, "metric": "p30", "model": "ql+rm3", "topic": "All Topics"}
2018-07-22 08:00:07,895 - regression_test - INFO - {"actual": 0.2498, "collection": "core17", "expected": 0.2498, "metric": "map", "model": "ql+ax", "topic": "All Topics"}
2018-07-22 08:00:07,982 - regression_test - INFO - {"actual": 0.4813, "collection": "core17", "expected": 0.4813, "metric": "p30", "model": "ql+ax", "topic": "All Topics"}
```

Did you turn off the `[OK]`?

**Comment by Peilin-Yang** [comment]
Now I use `info` and `error` to distinguish the successful and unsuccessful tests.
You will see `ERROR` with some `!`s https://github.com/castorini/Anserini/blob/master/src/main/python/run_regression.py#L164

**Comment by lintool** [comment]
Can we print a message like "All tests passed!" or something along those lines? That makes it easier to grep through multiple logs and make sure everything passes.

**Comment by lintool** [comment]
Update - all regressions have passed except for the ClueWeb ones.

**Comment by lintool** [comment]
Update - everything has passed except for full ClueWeb12, which is still running.

**Comment by lintool** [comment]
Full ClueWeb12 passes. Everything in new regression framework checks out.
