### ISSUE TITLE
Bugs with JDIQ regression experiments

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#385]
I'm getting the following when I try to run regressions:
```
jimmylin@tuna:/tuna1/scratch/jimmylin/Anserini$ python src/main/python/jdiq2018_effectiveness/run_batch.py --collection disk12
2018-08-05 07:21:17,084 - jdiq2018_effectiveness - INFO - ==========Batch Retrieval Parameters Generated==========
Traceback (most recent call last):
  File "src/main/python/jdiq2018_effectiveness/run_batch.py", line 186, in <module>
    batch_retrieval(collection_yaml, models_yaml, args.output_root)
  File "src/main/python/jdiq2018_effectiveness/run_batch.py", line 60, in batch_retrieval
    model_params = Search(index_path).gen_batch_retrieval_paras(topic['path'], models_yaml, this_output_root)
AttributeError: 'Search' object has no attribute 'gen_batch_retrieval_paras'
```

Also, there's broken link on this page: https://github.com/castorini/Anserini/blob/master/docs/experiments-jdiq2018.md 
(HERE points to nowhere)...

**Comment by lintool** [comment]
Fixed with #386
