### ISSUE TITLE
CACM regression failure

### ISSUE THREAD

**Issue by lintool** [castorini/Anserini#449]
We forgot to test the CACM regression in @r-clancy 's latest patch, so I think it broke the CACM regression. From CI -

```
$ python src/main/python/run_regression.py --collection cacm --index --fail_eval
...
2018-09-29 19:25:27,814 - regression_test - INFO - ==========Verifying Results==========
2018-09-29 19:25:27,882 - regression_test - ERROR - !!!!!{"actual": 0.3123, "collection": "cacm", "expected": 0.3102, "metric": "map", "model": "bm25", "topic": "CACM All"}!!!!!
Traceback (most recent call last):
  File "src/main/python/run_regression.py", line 228, in <module>
    eval_n_verify(yaml_data, args.fail_eval, args.dry_run)
  File "src/main/python/run_regression.py", line 185, in eval_n_verify
    assert False
AssertionError
```

**Comment by lintool** [comment]
Update, but then the latest failure is a JVM issue?

see: https://travis-ci.org/castorini/Anserini/builds/435726538

```
2018-10-01 17:15:08,178 - regression_test - INFO - ==========Indexing==========
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f0f2c000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8589934592 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/travis/build/castorini/Anserini/hs_err_pid5261.log
```
