### ISSUE TITLE
Indexing through symlinks

### ISSUE THREAD

**Issue by isoboroff** [castorini/Anserini#481]
This is initial playing, sorry if this is well-known.  I make a robust04 directory and symlinked in my normal locations for the CD45-cr subcollections, but it didn't work.  It seems that the filesystem walker either doesn't work over symlinks or crossing NFS boundaries:

```
$ cat log.robust04.pos+docvectors+rawdocs 
2018-11-21 15:21:56,782 INFO  [main] index.IndexCollection (IndexCollection.java:248) - DocumentCollection path: /Users/soboroff/robust04
2018-11-21 15:21:56,783 INFO  [main] index.IndexCollection (IndexCollection.java:249) - Index path: lucene-index.robust04.pos+docvectors
2018-11-21 15:21:56,783 INFO  [main] index.IndexCollection (IndexCollection.java:250) - CollectionClass: TrecCollection
2018-11-21 15:21:56,783 INFO  [main] index.IndexCollection (IndexCollection.java:251) - Generator: JsoupGenerator
2018-11-21 15:21:56,783 INFO  [main] index.IndexCollection (IndexCollection.java:252) - Threads: 16
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:253) - Stemmer: porter
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:254) - Keep stopwords? false
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:255) - Store positions? true
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:256) - Store docvectors? true
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:257) - Store transformed docs? false
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:258) - Store raw docs? true
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:259) - Optimize (merge segments)? false
2018-11-21 15:21:56,784 INFO  [main] index.IndexCollection (IndexCollection.java:260) - Whitelist: null
2018-11-21 15:21:56,799 INFO  [main] index.IndexCollection (IndexCollection.java:291) - Starting indexer...
2018-11-21 15:21:57,117 INFO  [main] index.IndexCollection (IndexCollection.java:314) - 4 files found in /Users/soboroff/robust04
2018-11-21 15:21:57,157 ERROR [pool-2-thread-1] index.IndexCollection$IndexerThread (IndexCollection.java:231) - pool-2-thread-1: Unexpected Exception:
java.io.FileNotFoundException: /Users/soboroff/robust04/FR94 (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_141]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_141]
	at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_141]
	at io.anserini.collection.TrecCollection$FileSegment.<init>(TrecCollection.java:83) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:59) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:43) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$IndexerThread.run(IndexCollection.java:187) [anserini-0.2.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-11-21 15:21:57,157 ERROR [pool-2-thread-2] index.IndexCollection$IndexerThread (IndexCollection.java:231) - pool-2-thread-2: Unexpected Exception:
java.io.FileNotFoundException: /Users/soboroff/robust04/LATIMES (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_141]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_141]
	at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_141]
	at io.anserini.collection.TrecCollection$FileSegment.<init>(TrecCollection.java:83) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:59) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:43) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$IndexerThread.run(IndexCollection.java:187) [anserini-0.2.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-11-21 15:21:57,157 ERROR [pool-2-thread-3] index.IndexCollection$IndexerThread (IndexCollection.java:231) - pool-2-thread-3: Unexpected Exception:
java.io.FileNotFoundException: /Users/soboroff/robust04/FT (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_141]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_141]
	at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_141]
	at io.anserini.collection.TrecCollection$FileSegment.<init>(TrecCollection.java:83) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:59) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:43) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$IndexerThread.run(IndexCollection.java:187) [anserini-0.2.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-11-21 15:21:57,157 ERROR [pool-2-thread-4] index.IndexCollection$IndexerThread (IndexCollection.java:231) - pool-2-thread-4: Unexpected Exception:
java.io.FileNotFoundException: /Users/soboroff/robust04/FBIS (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_141]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_141]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_141]
	at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_141]
	at io.anserini.collection.TrecCollection$FileSegment.<init>(TrecCollection.java:83) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:59) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.collection.TrecCollection.createFileSegment(TrecCollection.java:43) ~[anserini-0.2.1-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$IndexerThread.run(IndexCollection.java:187) [anserini-0.2.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-11-21 15:21:57,187 INFO  [main] index.IndexCollection (IndexCollection.java:359) - # Final Counter Values
2018-11-21 15:21:57,187 INFO  [main] index.IndexCollection (IndexCollection.java:360) - indexed:                0
2018-11-21 15:21:57,187 INFO  [main] index.IndexCollection (IndexCollection.java:361) - empty:                  0
2018-11-21 15:21:57,188 INFO  [main] index.IndexCollection (IndexCollection.java:362) - unindexed:              0
2018-11-21 15:21:57,188 INFO  [main] index.IndexCollection (IndexCollection.java:363) - unindexable:            0
2018-11-21 15:21:57,188 INFO  [main] index.IndexCollection (IndexCollection.java:364) - skipped:                0
2018-11-21 15:21:57,188 INFO  [main] index.IndexCollection (IndexCollection.java:365) - errors:                 0
2018-11-21 15:21:57,197 INFO  [main] index.IndexCollection (IndexCollection.java:368) - Total 0 documents indexed in 00:00:00
```

**Comment by lintool** [comment]
hi @isoboroff - welcome! This is the first report of such an issue... we're using standard Java file APIs, but we'll need to dig into the underlying behavior.

**Comment by Peilin-Yang** [comment]
@isoboroff 
Could you please try 
```
git fetch
git branch --track issue-481 origin/issue-481
git checkout issue-481
mvn clean package appassembler:assemble
```
and let us know?

**Comment by Peilin-Yang** [comment]
@isoboroff 
I think this is because that Anserini expects the input is a folder (not a single file).
See the help message of the `IndexCollection`: 
```
target/appassembler/bin/IndexCollection 
Option "-collection" is required
 -collection VAL              : collection class in io.anserini.collection
 -generator VAL               : document generator in io.anserini.index.generator
 -index [Path]                : index path
 -input [Directory]           : collection directory
```

Could you please post the directory tree if putting the file into a directory still does not work?

**Comment by isoboroff** [comment]
Ok.  I tested this by creating a 'robust04' directory and putting symlinks in there to the tops of my TREC-Disk-4 and 5 trees, which are over NFS to our central storage.  It is proceeding to index.  When the index completes I am curious how it deals with the non-document-bundles in those trees, I will check the log and reply again.  At any rate, the problem is fixed.

**Comment by lintool** [comment]
@isoboroff thanks!

**Comment by isoboroff** [comment]
Confirming it detects 0 documents in the DTD, AUX/, and .C files in those trees.  Maybe you knew that already.

**Comment by lintool** [comment]
@isoboroff Yup, this is what does the right thing: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/TrecCollection.java#L51
