### ISSUE TITLE
Dynamic vs. Static Mapping in ES

### ISSUE THREAD

**Issue by r-clancy** [castorini/anserini#732]
Currently, ES uses dynamic mapping to determine the type of fields. This caused us some issues with Solr, and appears to be happening in ES as well. For example, the `id_long` field in `mb11` (and `fullCaption` in `core18`) give the following errors because they're multi-valued:

```
2019-06-26 14:23:56,548 ERROR [pool-2-thread-31] index.IndexCollection$ESIndexerThread (IndexCollection.java:601) - Error sending bulk requests to Elasticsearch
com.fasterxml.jackson.core.JsonParseException: Duplicate field 'id_long'
 at [Source: (org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 64]
        at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:204) ~[jackson-core-2.9.9.jar:2.9.9]
        at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:198) ~[jackson-core-2.9.9.jar:2.9.9]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:734) ~[jackson-core-2.9.9.jar:2.9.9]
        at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:1877) ~[jackson-core-2.9.9.jar:2.9.9]
        at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:418) ~[elasticsearch-x-content-7.0.0.jar:7.0.0]
        at org.elasticsearch.common.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:988) ~[elasticsearch-x-content-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:239) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1429) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
        at io.anserini.index.IndexCollection$ESIndexerThread.sendBulkRequest(IndexCollection.java:597) [anserini-0.6.0-SNAPSHOT.jar:?]
        at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:554) [anserini-0.6.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
        Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
                at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1002) ~[elasticsearch-x-content-7.0.0.jar:7.0.0]
                at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:238) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
                at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1429) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
                at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
                at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
                at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
                at io.anserini.index.IndexCollection$ESIndexerThread.sendBulkRequest(IndexCollection.java:597) [anserini-0.6.0-SNAPSHOT.jar:?]
                at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:554) [anserini-0.6.0-SNAPSHOT.jar:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
                at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
        Caused by: java.io.IOException: Unclosed object or array found
                at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469) ~[elasticsearch-x-content-7.0.0.jar:7.0.0]
                at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1000) ~[elasticsearch-x-content-7.0.0.jar:7.0.0]
                ... 10 more
```

There are a number of methods for defining the mapping (field types), so it should be investigated to see which option makes the most sense while also fixing the errors with multi-valued fields above. On one end, we have [explicit mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_explicit_mappings) where the field types are defined beforehand. On the other end, we have [dynamic mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_dynamic_mapping) (the default) which tries to infer field types. The middle ground seems to be [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) where we can define field properties based on data type, name pattern, etc.

Can you take a look, @charW?

**Comment by r-clancy** [comment]
One more action item: update the ES BM25 search parameters to match Anserini and Solr's [values](https://github.com/castorini/anserini/blob/master/src/main/resources/solr/anserini/conf/managed-schema#L527).
