### ISSUE TITLE
Issue with SearchSolr

### ISSUE THREAD

**Issue by r-clancy** [castorini/anserini#814]
The following bug has slipped in when attempting to run the Solrini experiments:
```
2019-09-25 12:27:01,249 INFO  [main] search.SearchSolr (SearchSolr.java:165) - Solr index: robust04
2019-09-25 12:27:01,251 INFO  [main] search.SearchSolr (SearchSolr.java:166) - Solr ZooKeeper URL: localhost:9983
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-09-25 12:27:01,674 INFO  [main] search.SearchSolr$SolrSearcherThread (SearchSolr.java:124) - [Start] Retrieval with Solr collection: robust04
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
2019-09-25 12:27:02,221 ERROR [main] search.SearchSolr$SolrSearcherThread (SearchSolr.java:158) - main: Unexpected Exception:
java.lang.NullPointerException
    at io.anserini.rerank.lib.ScoreTiesAdjusterReranker.rerank(ScoreTiesAdjusterReranker.java:31) ~[anserini-0.6.1-SNAPSHOT.jar:?]
    at io.anserini.search.SearchSolr.search(SearchSolr.java:218) ~[anserini-0.6.1-SNAPSHOT.jar:?]
    at io.anserini.search.SearchSolr$SolrSearcherThread.run(SearchSolr.java:135) [anserini-0.6.1-SNAPSHOT.jar:?]
    at io.anserini.search.SearchSolr.runTopics(SearchSolr.java:194) [anserini-0.6.1-SNAPSHOT.jar:?]
    at io.anserini.search.SearchSolr.main(SearchSolr.java:271) [anserini-0.6.1-SNAPSHOT.jar:?]
2019-09-25 12:27:02,262 INFO  [main] search.SearchSolr (SearchSolr.java:274) - Total run time: 00:00:01
```

**Comment by lintool** [comment]
@r-clancy I think this issue can be closed?

**Comment by r-clancy** [comment]
@lintool Yep, closing now.
