### ISSUE TITLE
Elasticsearch exception

### ISSUE THREAD

**Issue by lintool** [castorini/anserini#888]
Using ES 7.4 on my Mac. Following instructions here: https://github.com/castorini/anserini/blob/master/docs/elastirini.md

Indexing seems to have proceeded successfully.

Running retrieval, I get:

```
$ sh target/appassembler/bin/SearchElastic -topicreader Trec -es.index robust04   -topics src/main/resources/topics-and-qrels/topics.robust04.txt   -output run.es.robust04.bm25.topics.robust04.txt
2019-11-23 05:22:33,166 INFO  [main] search.SearchElastic (SearchElastic.java:183) - Elasticsearch index: robust04
2019-11-23 05:22:33,167 INFO  [main] search.SearchElastic (SearchElastic.java:184) - Elasticsearch hostname: localhost
2019-11-23 05:22:33,167 INFO  [main] search.SearchElastic (SearchElastic.java:185) - Elasticsearch host port: 9200
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-11-23 05:22:33,414 INFO  [main] search.SearchElastic$ESSearcherThread (SearchElastic.java:142) - [Start] Retrieval with Elasticsearch collection: robust04
2019-11-23 05:22:33,641 ERROR [main] search.SearchElastic (SearchElastic.java:247) - Exception during ES query: 
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at io.anserini.search.SearchElastic.search(SearchElastic.java:244) [anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic$ESSearcherThread.run(SearchElastic.java:153) [anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic.runTopics(SearchElastic.java:216) [anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic.main(SearchElastic.java:321) [anserini-0.6.1-SNAPSHOT.jar:?]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/robust04/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"robust04","node":"bfgKhiTDQWanXWuZtyNMdg","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}},"status":400}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
		at io.anserini.search.SearchElastic.search(SearchElastic.java:244) [anserini-0.6.1-SNAPSHOT.jar:?]
		at io.anserini.search.SearchElastic$ESSearcherThread.run(SearchElastic.java:153) [anserini-0.6.1-SNAPSHOT.jar:?]
		at io.anserini.search.SearchElastic.runTopics(SearchElastic.java:216) [anserini-0.6.1-SNAPSHOT.jar:?]
		at io.anserini.search.SearchElastic.main(SearchElastic.java:321) [anserini-0.6.1-SNAPSHOT.jar:?]
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:598) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[elasticsearch-7.0.0.jar:7.0.0]
	... 10 more
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:598) ~[elasticsearch-7.0.0.jar:7.0.0]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[elasticsearch-7.0.0.jar:7.0.0]
	... 10 more
2019-11-23 05:22:33,645 ERROR [main] search.SearchElastic$ESSearcherThread (SearchElastic.java:176) - main: Unexpected Exception:
java.lang.NullPointerException
	at io.anserini.rerank.ScoredDocuments.fromESDocs(ScoredDocuments.java:100) ~[anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic.search(SearchElastic.java:251) ~[anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic$ESSearcherThread.run(SearchElastic.java:153) [anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic.runTopics(SearchElastic.java:216) [anserini-0.6.1-SNAPSHOT.jar:?]
	at io.anserini.search.SearchElastic.main(SearchElastic.java:321) [anserini-0.6.1-SNAPSHOT.jar:?]
2019-11-23 05:22:33,655 INFO  [main] search.SearchElastic (SearchElastic.java:324) - Total run time: 00:00:00
```

**Comment by lintool** [comment]
Fixed by #907
