### ISSUE TITLE
JaCoCo maven plugin causing build error on OSX

### ISSUE THREAD

**Issue by bevankoopman** [castorini/anserini#967]
I get the following exception on Maven build, while running tests, after clean clone of anserini:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_28bab1d.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_28bab1d.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
/bin/sh: line 1: 11536 Abort trap: 6           /usr/local/Cellar/openjdk/13.0.2+8/libexec/openjdk.jdk/Contents/Home/bin/java -javaagent:/Users/koo01a/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/koo01a/tools/anserini/target/jacoco.exec -jar /Users/koo01a/tools/anserini/target/surefire/surefirebooter1045580172235412003.jar /Users/koo01a/tools/anserini/target/surefire/surefire3369881099308680003tmp /Users/koo01a/tools/anserini/target/surefire/surefire_07744071255521598417tmp
```

Removing `jacoco-maven-plugin` from the `pom.xml` fixes this.

Environment:

- OpenJDK 13.0.2
- Apache Maven 3.6.3
- macOS 10.14.3

**Comment by lintool** [comment]
This might be a JDK 13 issue? See: https://github.com/jacoco/jacoco/issues/828

**Comment by bevankoopman** [comment]
Ok. Downgraded to JDK 11 and confirm that tests all pass now.

**Comment by lintool** [comment]
Thanks for the follow-up. Closing issue.
